# Generated by Django 5.2.7 on 2025-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide the app everywhere without deleting it.",
                    ),
                ),
                (
                    "show_in_dashboard",
                    models.BooleanField(
                        default=True,
                        help_text="Controls if this appears as a card on the dashboard.",
                    ),
                ),
                (
                    "hero_image",
                    models.URLField(
                        blank=True,
                        help_text="Optional image URL for the app detail page hero section.",
                    ),
                ),
                (
                    "coming_soon_message",
                    models.TextField(
                        blank=True,
                        help_text="Optional longer message for the coming soon page.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to make the app available to all authenticated users.",
                        related_name="dashboard_apps",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
