# Generated by Django 5.2.8 on 2025-11-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_komlineitem_value_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='komform',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Raw parsed data from Excel file as JSON', null=True),
        ),
    ]
