# Generated by Django 5.2.8 on 2025-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_komform_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='komform',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='kom_files/%Y/%m/'),
        ),
    ]
