# Generated by Django 5.2.8 on 2025-11-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_komform_uploaded_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komform',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='komform',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
