# Generated by Django 5.2.8 on 2025-11-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_komform_uploaded_file_komform_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='komform',
            name='job_number',
            field=models.CharField(blank=True, db_index=True, help_text='5-digit job number extracted from proposal number', max_length=10),
        ),
    ]
