# Generated by Django 5.2.7 on 2025-11-04 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Event title (required)", max_length=200
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Event start date and time"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="Event end date and time"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional event description"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Optional event location", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Event owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["user", "start_datetime"],
                        name="my_calendar_user_id_6259cd_idx",
                    ),
                    models.Index(
                        fields=["start_datetime", "end_datetime"],
                        name="my_calendar_start_d_3f8292_idx",
                    ),
                ],
            },
        ),
    ]
