# Generated by Django 5.2.6 on 2025-11-07 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('inventor_file_path', models.CharField(blank=True, help_text='Path to Inventor assembly file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assemblies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Component name as it appears in Inventor', max_length=255)),
                ('inventor_instance_name', models.CharField(blank=True, help_text="Instance name in Inventor (e.g., ':1')", max_length=255)),
                ('component_type', models.CharField(blank=True, help_text='Type: Flange, Pipe, Tank, etc.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='ilogic.assembly')),
                ('parent_component', models.ForeignKey(blank=True, help_text='Parent component in hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_components', to='ilogic.component')),
            ],
            options={
                'ordering': ['assembly', 'name'],
                'unique_together': {('assembly', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Configurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('input_parameters', models.JSONField(blank=True, default=dict, help_text='Default input parameters')),
                ('output_bom', models.JSONField(blank=True, default=dict, help_text='Generated BOM structure')),
                ('simulation_results', models.JSONField(blank=True, default=dict, help_text='Last simulation results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurators', to='ilogic.assembly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['assembly', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='Name of the rule in Inventor', max_length=255)),
                ('rule_code', models.TextField(help_text='Full iLogic VBA code')),
                ('rule_type', models.CharField(choices=[('parameter', 'Parameter'), ('iproperty', 'iProperty'), ('part_number', 'Part Number'), ('description', 'Description'), ('mixed', 'Mixed'), ('other', 'Other')], default='mixed', max_length=50)),
                ('triggers', models.JSONField(blank=True, default=list, help_text="List of parameters that trigger this rule (e.g., ['FlangeSize', 'MATERIAL'])")),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of other rules/components this depends on')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Extracted data: part numbers, parameters, etc.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ilogic.component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['component', 'rule_name'],
                'unique_together': {('component', 'rule_name')},
            },
        ),
        migrations.CreateModel(
            name='Inconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('description_mismatch', 'Description Mismatch (e.g., SS316 says SS304)'), ('missing_part_number', 'Missing Part Number (XXX placeholder)'), ('duplicate_part_number', 'Duplicate Part Number'), ('logic_inconsistency', 'Logic Inconsistency'), ('missing_condition', 'Missing Condition'), ('parameter_mismatch', 'Parameter Mismatch'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('description', models.TextField(help_text='Description of the inconsistency')),
                ('affected_components', models.JSONField(blank=True, default=list, help_text='List of affected component names')),
                ('suggested_fix', models.TextField(blank=True, help_text='Suggested fix for this issue')),
                ('code_location', models.CharField(blank=True, help_text='Location in code (line numbers, etc.)', max_length=500)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True)),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='ilogic.assembly')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='ilogic.component')),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_inconsistencies', to=settings.AUTH_USER_MODEL)),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencies', to='ilogic.rule')),
            ],
            options={
                'verbose_name_plural': 'Inconsistencies',
                'ordering': ['-severity', '-found_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('code_snapshot', models.TextField()),
                ('change_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ilogic.rule')),
            ],
            options={
                'ordering': ['rule', '-version_number'],
                'unique_together': {('rule', 'version_number')},
            },
        ),
    ]
